### ISSUE TITLE
Can't download the weight?

### ISSUE THREAD

**Issue by PumayHui** [zhaoweicai/Detectron-Cascade-RCNN#14]
When I train the model with "configs/e2e_cascade_rcnn_R-101-FPN_1x_gn.yaml", it shows such errors:

> INFO io.py:  67: Downloading remote file https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/47592356/R-101-GN.pkl to /tmp/detectron-download-cache/ImageNetPretrained/47592356/R-101-GN.pkl
Traceback (most recent call last):
  File "tools/train_net.py", line 132, in <module>
    main()
  File "tools/train_net.py", line 101, in main
    assert_and_infer_cfg()
  File "/home/test/Detectron-Cascade-RCNN/detectron/core/config.py", line 1127, in assert_and_infer_cfg
    cache_cfg_urls()
  File "/home/test/Detectron-Cascade-RCNN/detectron/core/config.py", line 1136, in cache_cfg_urls
    __C.TRAIN.WEIGHTS = cache_url(__C.TRAIN.WEIGHTS, __C.DOWNLOAD_CACHE)
  File "/home/test/Detectron-Cascade-RCNN/detectron/utils/io.py", line 68, in cache_url
    download_url(url, cache_file_path)
  File "/home/test/Detectron-Cascade-RCNN/detectron/utils/io.py", line 114, in download_url
    response = urllib2.urlopen(url)
  File "/home/dl/anaconda3/envs/caffe2_py2/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/dl/anaconda3/envs/caffe2_py2/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/dl/anaconda3/envs/caffe2_py2/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/dl/anaconda3/envs/caffe2_py2/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/dl/anaconda3/envs/caffe2_py2/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/dl/anaconda3/envs/caffe2_py2/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

And I try to “wget https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/47592356/R-101-GN.pkl”， it also failured.

Can anyone show me where is the model "https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/47592356/R-101-GN.pkl"?

**Comment by ZhiHuaYin** [comment]
find the weight : [https://github.com/facebookresearch/Detectron/](https://github.com/facebookresearch/Detectron/)
